name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2 # This action sets up MSBuild environment by finding the path to MSBuild.exe.        
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          dir ${{ github.workspace }}
          
      - name: Set up MSBuild path
        run: msbuild ${{ github.workspace }}\netlab\NetlabTAU.sln /p:Configuration=Debug /p:Platform=win32 /t:netlab_testing
        env:
            IncludePath: ${{ github.workspace }}\Dependency_Libraries\WpdPack_4_1_2\WpdPack\Include;${{ github.workspace }}\Dependency_Libraries\pthreads-w32-2-9-1-release\Pre-built.2\include;${{ github.workspace }}\Dependency_Libraries\boost_1_83_0;${{ github.workspace }}\Dependency_Libraries\googletest-1.14.0\googletest\include
        shell: cmd
        
      - name: Run UDP Tests
        run: .\netlab_testing.exe
        working-directory: .\netlab\Debug
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
             token: ${{ secrets.CODECOV_TOKEN }}
             slug: GabrielKlyatis/NetlabTAU
      - run: echo "🍏 This job's status is ${{ job.status }}."
